[build]
  publish = "."

[[redirects]]
  from = "/spark"
  to = "/SPARK/index.html"
  status = 200

[[redirects]]
  from = "/spark/"
  to = "/SPARK/index.html"
  status = 200

[[redirects]]
  from = "/SPARK"
  to = "/SPARK/index.html"
  status = 200

[[redirects]]
  from = "/CILAB"
  to = "/CILAB/index.html"
  status = 200

[[redirects]]
  from = "/cilab"
  to = "/CILAB/index.html"
  status = 200

[[redirects]]
  from = "/cilab/"
  to = "/CILAB/index.html"
  status = 200
