title: "Sophie Bijjani"
tagline: "Inspire, exprime"
hero_title: "Bienvenue dans mon univers musical"
hero_description: "Test 123!"
contact_title: "Me contacter"
contact_info: |
  Email : contact@monsite.com
  Téléphone : Oublie ça 
