title: "Sophie Bijjani"
tagline: "Inspire, exprime"
hero_title: "Bienvenue sur mon site"
hero_description: "Ce texte peut être modifié facilement via l'interface d'administration. Pas besoin de toucher au code !"
contact_title: "Me contacter"
contact_info: |
  Email : contact@monsite.com
  Téléphone : Oublie ça 
